apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: student0
  name: student0-deployment
spec:
  selector:
    matchLabels:
      app: student0
  template:
    metadata:
      labels:
        app: student0
    spec:
      containers:
      - name: student0
        image: registry.tanzu.dk/ops2devops/student0:v1
